# Generated by Django 6.0.4 on 2026-04-27 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('delivery', '0001_initial'),
        ('lr_booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TURCaseId',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_id', models.CharField(max_length=20, null=True, unique=True)),
                ('date', models.DateField()),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('flag', models.BooleanField(default=True)),
                ('branch_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tur_case_branch', to='branches.branchmaster')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='tur_case_created_by', to=settings.AUTH_USER_MODEL)),
                ('lr_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lr_tur_cases', to='lr_booking.lr_bokking')),
                ('tur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tur_cases', to='delivery.truckunloadingreport')),
                ('tur_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tur_detail_cases', to='delivery.truckunloadingreportdetails')),
                ('tur_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tur_case_status', to='delivery.truckunloadingreportstatus')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tur_case_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tur_case_id',
            },
        ),
    ]
