# Generated by Django 5.2.8 on 2026-04-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=150)),
                ('short_name', models.CharField(max_length=20)),
                ('branch_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=50)),
                ('account_holder_name', models.CharField(max_length=150)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('account_type', models.CharField(choices=[('saving', 'Saving'), ('current', 'Current')], default='current', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bank_master',
                'managed': False,
            },
        ),
    ]
