# Generated by Django 5.2.8 on 2026-04-06 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_bankmaster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankmaster',
            options={'managed': True},
        ),
    ]
