# Generated by Django 5.2.8 on 2026-04-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_bankmaster_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankmaster',
            options={'managed': False},
        ),
    ]
