# Generated by Django 6.0.4 on 2026-04-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_bankmaster_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='partybilling',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
