# Generated by Django 6.0.4 on 2026-04-25 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_partybilling_advance_amount'),
        ('branches', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeCaseId',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_id', models.CharField(max_length=20, null=True, unique=True)),
                ('date', models.DateField()),
                ('cheque_no', models.CharField(max_length=100)),
                ('cheque_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CLEARED', 'CLEARED'), ('BOUNCED', 'BOUNCED')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('flag', models.BooleanField(default=True)),
                ('bank_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheque_case_bank', to='account.bankmaster')),
                ('branch_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheque_case_branch', to='branches.branchmaster')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='cheque_case_created_by', to=settings.AUTH_USER_MODEL)),
                ('mr_no', models.ForeignKey(blank=True, db_column='mr_no', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheque_case_ids', to='account.moneyreceipt', to_field='mr_no')),
                ('party_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheque_case_party', to='parties.partymaster')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheque_case_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
