# Generated by Django 6.0.4 on 2026-05-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_bookingmemolrs_drop_at_branch_vehicleparkdispatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleparkdispatch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
