# Generated by Django 6.0.4 on 2026-04-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routestations',
            options={'ordering': ['sequence_order']},
        ),
        migrations.AddField(
            model_name='routestations',
            name='sequence_order',
            field=models.PositiveIntegerField(default=1, help_text='Order of this stop along the route (1-based)'),
        ),
        migrations.AddField(
            model_name='routestations',
            name='stop_type',
            field=models.CharField(choices=[('INTERMEDIATE', 'Intermediate'), ('FINAL', 'Final')], default='INTERMEDIATE', help_text='INTERMEDIATE = part-load drop point; FINAL = terminal destination', max_length=20),
        ),
    ]
